### ISSUE TITLE
Standalone program: generate web visualization similar to webserver

### ISSUE THREAD

**Issue by najibveto** [DSIMB/MEDUSA#1]
hello,
thank you for your new tool.
i could installed easily and it works fine.
just i would like to know if it possible to generate visualization similar to web server.
thank you for your help.

**Comment by gabrielctn** [comment]
Hi,
Thank you for your interest in MEDUSA and for using it !
Yes it is something we can plan to implement in the next few weeks.
We lack a bit of time at the moment but watch the repo to not miss the update 👍🏼

**Comment by najibveto** [comment]
thanks a lot for your efforts.
